#!/bin/bash

NC='\033[0;37m'
COLOR1='\033[0;34m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BICyan='\033[0;34m' 
BIWhite='\033[1;97m'  
red() { echo -e "\\033[31;1m${*}\\033[0m"; }

function uservless(){
clear
NUMBER_OF_CLIENTS=$(grep -c -E "^#& " "/etc/xray/config.json")
        if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    echo -e "\033[1;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e " \e[1;97;101m         CONFIG VLESS ACCOUNT           \e[0m"
    echo -e "\033[1;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo ""
    echo "You have no existing clients!"
    echo ""
    echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    read -n 1 -s -r -p "Press [ Enter ] to back on menu vless"
    m-vless
fi

  echo -e "\033[1;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo -e "  \e[1;97;101m        CONFIG VLESS ACCOUNT         \E[0m"
  echo -e "\033[1;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
        echo "     No  Expired   User"
        grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2-3 | nl -s ') '
        until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
                if [[ ${CLIENT_NUMBER} == '1' ]]; then
                        read -rp "Select one client [1]: " CLIENT_NUMBER
                else
                        read -rp "Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
                fi
        done
user=$(grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
domain=$(cat /etc/xray/domain)
iplim=$(cat /etc/kyt/limit/vless/ip/$user)
Quota=$(cat /etc/vless/$user)
uuid=$(grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 4 | sed -n "${CLIENT_NUMBER}"p)
exp=$(grep -E "^#& " "/etc/xray/config.json" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)

vlesslink1="vless://${uuid}@${domain}:443?encryption=none&security=tls&sni=${domain}&type=ws&host=${domain}&path=%2Fvless#${user}-WS-TLS"
vlesslink2="vless://${uuid}@${domain}:80?encryption=none&security=none&type=ws&host=${domain}&path=%2Fvless#${user}-WS-NTLS"
vlesslink3="vless://${uuid}@${domain}:443?encryption=none&security=tls&sni=${domain}&type=grpc&serviceName=vless-grpc&mode=gun#${user}-gRPC"

clear
echo -e ""
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e " Xray/Vless Account "
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Remarks          : ${user}"
echo -e "Domain           : ${domain}"
echo -e "User Quota       : ${Quota} GB"
echo -e "User Ip          : ${iplim} IP"
echo -e "Port TLS         : 443, 8443, 2087, 2096"
echo -e "Port none TLS    : 80, 8080, 8880, 2082"
echo -e "User ID          : ${uuid}"
echo -e "Encryption       : none"
echo -e "Path TLS         : /vless "
echo -e "ServiceName      : vless-grpc"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Link TLS         : ${vlesslink1}"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Link NTLS        : ${vlesslink2}"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Link GRPC        : ${vlesslink3}"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Format OpenClash : https://${domain}:81/vless-$user.txt"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e "Berakhir Pada    : $exp"
echo -e "\033[0;34m◇━━━━━━━━━━━━━━━━━◇\033[0m"
echo -e " "
echo -e "\033[0;32m zaker240091-bit 082328013583 ${NC}"
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
m-vless
}

clear
echo -e "${BICyan}┌─────────────────────────────────────────────────┐${NC}"
echo -e "${BICyan}│\e[1;97;101m                   VLESS MENU                    ${BICyan}│$NC"
echo -e "${BICyan}└─────────────────────────────────────────────────┘${NC}"
echo -e " ${BICyan}┌───────────────────────────────────────────────┐${NC}"
echo -e "     ${COLOR1}[${BIWhite}1${COLOR1}] ${NC}Create Vless Account     "
echo -e "     ${COLOR1}[${BIWhite}2${COLOR1}] ${NC}Trial Vless Acoount     "
echo -e "     ${COLOR1}[${BIWhite}3${COLOR1}] ${NC}Delete Account Vless     "
echo -e "     ${COLOR1}[${BIWhite}4${COLOR1}] ${NC}Renew Account Vless     "
echo -e "     ${COLOR1}[${BIWhite}5${COLOR1}] ${NC}Cek User Login Account Vless     "
echo -e "     ${COLOR1}[${BIWhite}6${COLOR1}] ${NC}View Config Account Vless     "
echo -e "     ${COLOR1}[${BIWhite}0${COLOR1}] ${NC}Back To Menu     "
echo -e " "
echo -e "     \e[1;97;101m✶ Install by zaker240091-bit 082328013583 082328013583 ✶ ${NC} "
echo -e " ${BICyan}└──────────────────────────────────────────────┘${NC}"
echo ""
read -p " Select menu : " opt
echo -e ""
case $opt in
1) clear ; addvless ;;
2) clear ; trialvless ;;
3) clear ; delvless ;;
4) clear ; renewvless ;;
5) clear ; cekvless ;;
6) clear ; uservless ;;
0) clear ; menu ;;
x) exit ;;
*) echo -e "" ; echo "Press any key to back on menu" ; sleep 1 ; menu ;;
esac
